config:
  workingRootDir: gxen/
type:
  rootDir: seed/
  defaultTemplateFileRootDir: seed/tmpl/
  defaultSettingFileRootDir: seed/yaml/
code:
  rootDir: template/
  generatedTestCodeRootDir: __test__/
  generatedCodeRootDir: app/
extension:
  settingExtension: .yaml
  generatedCodeExtension: .ts
  templateExtension: .tmpl
  testExtension: .test
